#!/usr/bin/env bash
# redirection
sudo apt-get update -y
sudo apt-get install nginx -y
sudo sed -i "30i \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=SK9KEwE6JmE permanent;" /etc/nginx/sites-available/default
sudo sed -i "30i \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=SK9KEwE6JmE permanent;" /etc/nginx/sites-enabled/default
sudo service nginx start
