#!/usr/bin/env bash
# redirection
apt-get update -y
apt-get install nginx -y
sed '37a\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
service nginx start
