#!/usr/bin/env bash
# redirection
sudo apt-get update -y
sudo apt-get install nginx -y
sudo sed '37a\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
sudo service nginx start
