#!/usr/bin/env bash
# HAProxy
sudo apt-get install software-properties-common -y
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-1.8 -y
sudo apt-get update -y
sudo apt-get install haproxy=1.8.\* -y
front="\nfrontend haproxynode\n\tbind *:80\n\tdefault_backend back_nodes\n"
back="\nbackend back_nodes\n\tbalance roundrobin\n\tserver 792-web-01 34.74.58.19 check\n\tserver 792-web-02 35.190.145.187 check"
echo -e $front | sudo tee --append /etc/haproxy/haproxy.cfg
echo -e $back | sudo tee --append /etc/haproxy/haproxy.cfg
sudo service haproxy restart
