#!/usr/bin/env bash
#Process and PID fike
echo $$ > '/var/run/holbertonscript.pid'

trap "echo 'Y U no love me?!'" SIGINT
trap clean_up SIGQUIT SIGTERM
clean_up() {
    echo 'I hate the kill command'
    rm /var/run/holbertonscript.pid
    exit
}
while true
do
    echo "To infinity and beyond"
    sleep 2
done
clean_up
