#!/usr/bin/env bash
#Process and PID fike
echo "$$" > /var/run/holbertonscript.pid

trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap clean_up SIGQUIT SIGTERM
clean_up() {
    rm /var/run/holbertonscript.pid
    exit
}
while true
do
    echo "To infinity and beyond"
done
clean_up
