#!/usr/bin/env bash
# configure an Ubuntu server with the below requirements.
cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost/' ~/hosts.new
sed -i '2c\8.8.8.8 facebook.com' ~/hosts.new
sed -i 's/^:/# :/' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
